version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run test-jest
reports:
  jest_reports:
    files:
      - jest-report
    file-format: JUNITXML
    base-directory: ./testing-reports